version: '2'
services:
  web:
    build: ./
    command: npm run server
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/logs/null
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /data
    restart: always